import type { Training, TrainingCategory } from "@/types";

export const trainingCategoryLabels: Record<TrainingCategory, string> = {
  warmup: "Calentamiento",
  technique: "Tecnica individual",
  passing: "Pase y recepcion",
  dribbling: "Conduccion y regate",
  control: "Control y primer toque",
  finishing: "Finalizacion",
  heading: "Juego de cabeza",
  possession: "Posesion y rondos",
  positional: "Juego de posicion",
  transitions: "Transiciones",
  pressing: "Presion",
  defending: "Defensa",
  setpieces: "Pelota parada (ABP)",
  smallsided: "Juegos reducidos",
  goalkeeper: "Porteros",
  physical: "Preparacion fisica",
  "futsal-specific": "Especificos futsal",
};

export const trainings: readonly Training[] = [
  {
    id: "warmup-articular",
    name: "Activacion articular progresiva",
    category: "warmup",
    objective: "Preparar el cuerpo, elevar pulsaciones y prevenir lesiones.",
    formats: ["football11", "football8", "football7", "futsal"],
    playersMin: 6,
    playersMax: 25,
    durationMin: 8,
    durationMax: 10,
    materials: [{ name: "Balones", count: 1 }],
    description: [
      "Trote suave 2 min en circulo, cada uno con su balon rodando.",
      "Movilidad articular: tobillo, rodilla, cadera, tronco, hombros y cuello (30s cada uno).",
      "Skipping bajo, skipping alto, talones a gluteos, zancadas, desplazamientos laterales, carioca (20 m c/u).",
      "Estiramientos dinamicos: balanceos pierna adelante/atras, lateral, abrazo de rodilla, soldadito.",
    ],
    indicators: ["Buena ejecucion tecnica", "Ausencia de molestias"],
  },
  {
    id: "warmup-rondo-5v2",
    name: "Rondo de calentamiento 5v2",
    category: "warmup",
    objective: "Activar tecnicamente con primer toque y pase corto bajo presion.",
    formats: ["football11", "football8", "football7", "futsal"],
    playersMin: 7,
    playersMax: 7,
    durationMin: 8,
    durationMax: 8,
    space: "Circulo de 8-10 m de diametro",
    materials: [
      { name: "Conos", count: 8 },
      { name: "Balones", count: 1 },
      { name: "Petos", count: 2 },
    ],
    description: [
      "5 jugadores exteriores en el circulo, 2 jugadores adentro.",
      "Maximo 2 toques.",
      "Quien pierde el balon o realiza un pase fallado pasa al centro.",
    ],
    variants: [
      "Solo 1 toque obligatorio",
      "Pase al jugador no adyacente",
      "10 pases seguidos suman 1 punto",
    ],
  },
  {
    id: "warmup-conduccion",
    name: "Conduccion en espacio reducido",
    category: "warmup",
    objective: "Activar con balon, percepcion del entorno y respuesta a estimulos.",
    formats: ["football11", "football8", "football7", "futsal"],
    playersMin: 10,
    playersMax: 20,
    durationMin: 6,
    durationMax: 6,
    space: "20 x 20 m",
    materials: [{ name: "Balones (uno por jugador)", count: 20 }],
    description: [
      "Cada jugador conduce su balon dentro del area evitando choques.",
      "Senal '1': frenar con planta.",
      "Senal '2': cambio de direccion.",
      "Senal '3': pase al companero mas cercano.",
      "Senal '4': aceleracion de 5 m.",
    ],
    variants: ["Solo pie debil", "Solo borde externo", "Solo borde interno"],
  },
  {
    id: "tech-juggling",
    name: "Toques y malabares (juggling)",
    category: "technique",
    objective: "Sensibilidad de balon, equilibrio y coordinacion.",
    formats: ["football11", "football8", "football7", "futsal"],
    playersMin: 1,
    playersMax: 30,
    durationMin: 5,
    durationMax: 10,
    materials: [{ name: "Balones (uno por jugador)", count: 30 }],
    description: [
      "Empeine derecho: 5, 10, 20 toques sin que caiga.",
      "Lo mismo con el empeine izquierdo.",
      "Alternar pies.",
      "Combinar muslo y pie.",
      "Combinar cabeza y pie.",
      "Por parejas: maximo de toques sin que caiga.",
    ],
  },
  {
    id: "tech-circuit-8",
    name: "Circuito tecnico individual de 8 estaciones",
    category: "technique",
    objective: "Trabajar todos los fundamentos sin oposicion.",
    formats: ["football11", "football8", "football7", "futsal"],
    playersMin: 8,
    playersMax: 16,
    durationMin: 20,
    durationMax: 25,
    materials: [
      { name: "Conos", count: 30 },
      { name: "Balones", count: 8 },
      { name: "Porteria chica", count: 1 },
    ],
    description: [
      "1) Conduccion en zigzag entre 6 conos separados 1.5 m.",
      "2) Pase contra pared y control orientado.",
      "3) Slalom + remate a porteria pequena.",
      "4) Juggling individual.",
      "5) Cambios de direccion con balon en cono central (4 puntos).",
      "6) Pase corto-largo: 5 m + 15 m alternados.",
      "7) Conduccion explosiva 10 m + frenada.",
      "8) Definicion 1v0 a porteria con portero.",
      "Dos vueltas: 1 min por estacion + 30s de descanso.",
    ],
  },
  {
    id: "pass-cuadrado",
    name: "Cuadrado de pase 4 esquinas",
    category: "passing",
    objective: "Pase preciso, orientacion corporal y rotaciones.",
    formats: ["football11", "football8", "football7", "futsal"],
    playersMin: 4,
    playersMax: 8,
    durationMin: 10,
    durationMax: 10,
    space: "12 x 12 m",
    materials: [
      { name: "Conos", count: 4 },
      { name: "Balones", count: 1 },
    ],
    description: [
      "Un jugador en cada esquina, balon en una.",
      "Pasa al siguiente y corre a la posicion a la que paso.",
      "Rotacion continua.",
    ],
    variants: [
      "Pase + sprint a la siguiente esquina",
      "Pase con borde exterior",
      "Dos balones simultaneos en diagonales",
      "Pase diagonal (al jugador no adyacente)",
      "Pase de pared con jugador interior",
    ],
  },
  {
    id: "pass-triangulacion",
    name: "Triangulacion con apoyos",
    category: "passing",
    objective: "Pase, control orientado y desmarques de apoyo.",
    formats: ["football11", "football8", "football7", "futsal"],
    playersMin: 3,
    playersMax: 12,
    durationMin: 6,
    durationMax: 8,
    space: "Triangulo de 10 x 10 x 10 m",
    materials: [
      { name: "Conos", count: 3 },
      { name: "Balones", count: 1 },
    ],
    description: [
      "A pasa a B, B controla orientado y pasa a C, C controla y pasa a A.",
      "Trabajar sentido horario y antihorario.",
    ],
    variants: [
      "Pase + desmarque al vertice opuesto",
      "1 toque obligatorio",
      "Pared entre A-B antes de pasar a C",
    ],
  },
  {
    id: "pass-rondo-4v1",
    name: "Rondo 4v1",
    category: "passing",
    objective: "Lineas de pase y reaccion bajo presion.",
    formats: ["football11", "football8", "football7", "futsal"],
    playersMin: 5,
    playersMax: 5,
    durationMin: 8,
    durationMax: 10,
    space: "6 x 6 m",
    materials: [
      { name: "Conos", count: 4 },
      { name: "Balones", count: 1 },
    ],
    description: [
      "4 exteriores en el cuadrado, 1 jugador adentro como recuperador.",
      "Maximo 2 toques.",
      "8 pases seguidos suman 1 punto.",
      "Quien pierde la pelota entra al centro.",
    ],
    variants: ["Solo 1 toque", "Pase al jugador opuesto vale 2 puntos"],
  },
  {
    id: "dribble-1v1-frontal",
    name: "1v1 frontal con definicion",
    category: "dribbling",
    objective: "Variedad de regates, cambio de ritmo y finalizacion.",
    formats: ["football11", "football8", "football7", "futsal"],
    playersMin: 8,
    playersMax: 20,
    durationMin: 10,
    durationMax: 12,
    space: "20 x 10 m con porteria",
    materials: [
      { name: "Conos", count: 6 },
      { name: "Balones", count: 6 },
      { name: "Porteria", count: 1 },
    ],
    description: [
      "Atacante con balon enfrenta a defensor desde 8 m.",
      "Busca superarlo y finalizar a porteria.",
      "Cambio de roles en cada repeticion.",
    ],
    indicators: ["Variedad de regates", "Cambio de ritmo claro", "Finalizacion efectiva"],
  },
  {
    id: "dribble-calle",
    name: "Calle de regates",
    category: "dribbling",
    objective: "Practica de distintos regates en serie.",
    formats: ["football11", "football8", "football7", "futsal"],
    playersMin: 6,
    playersMax: 20,
    durationMin: 12,
    durationMax: 15,
    space: "Pasillo 20 x 3 m con defensores estaticos cada 4 m",
    materials: [
      { name: "Conos", count: 6 },
      { name: "Balones", count: 6 },
    ],
    description: [
      "Cada atacante recorre el pasillo superando 4-5 defensores estaticos.",
      "Aplicar un regate distinto en cada uno: bicicleta, ruleta, autopase, croqueta, recorte.",
    ],
  },
  {
    id: "finish-estrella",
    name: "Circuito de finalizacion 'estrella'",
    category: "finishing",
    objective: "Definicion a un toque desde distintos angulos.",
    formats: ["football11", "football8", "football7"],
    playersMin: 6,
    playersMax: 14,
    durationMin: 12,
    durationMax: 15,
    space: "Frontal del area con 5 conos en abanico (10-18 m)",
    materials: [
      { name: "Conos", count: 5 },
      { name: "Balones", count: 10 },
      { name: "Porteria", count: 1 },
    ],
    description: [
      "El jugador recibe pase del entrenador desde cada cono y define al angulo.",
      "5 disparos seguidos por jugador.",
      "Variar pierna y altura del pase recibido.",
    ],
  },
  {
    id: "finish-centros",
    name: "Finalizacion tras centro desde banda",
    category: "finishing",
    objective: "Centros precisos y llegadas al area.",
    formats: ["football11", "football8", "football7"],
    playersMin: 6,
    playersMax: 14,
    durationMin: 15,
    durationMax: 20,
    materials: [
      { name: "Conos", count: 4 },
      { name: "Balones", count: 8 },
      { name: "Porteria", count: 1 },
    ],
    description: [
      "Extremo conduce por banda y centra.",
      "Dos rematadores en el area: uno al primer palo, otro al segundo.",
      "Variar tipos de centro: raso, alto, atras, segundo palo.",
    ],
  },
  {
    id: "poss-4v4-comodines",
    name: "Posesion 4v4 + 2 comodines",
    category: "possession",
    objective: "Mantener la pelota usando apoyos exteriores.",
    formats: ["football11", "football8", "football7", "futsal"],
    playersMin: 10,
    playersMax: 10,
    durationMin: 12,
    durationMax: 15,
    space: "20 x 20 m",
    materials: [
      { name: "Conos", count: 4 },
      { name: "Petos", count: 8 },
      { name: "Balones", count: 1 },
    ],
    description: [
      "Dos equipos de 4 jugadores. Dos comodines neutrales siempre con el equipo en posesion.",
      "Objetivo: 10 pases consecutivos suman 1 punto.",
      "3 series de 3 min, descanso de 1 min entre series.",
    ],
    variants: ["Maximo 2 toques", "Comodin solo a 1 toque", "Pase obligatorio al comodin cada 4 pases"],
  },
  {
    id: "poss-zonas",
    name: "Posesion por zonas (3 franjas)",
    category: "possession",
    objective: "Progresion del juego por zonas y jerarquia posicional.",
    formats: ["football11", "football8", "football7"],
    playersMin: 12,
    playersMax: 12,
    durationMin: 12,
    durationMax: 15,
    space: "30 x 20 m, dividido en 3 franjas verticales",
    materials: [
      { name: "Conos", count: 10 },
      { name: "Petos", count: 12 },
      { name: "Balones", count: 1 },
    ],
    description: [
      "2v2 en cada franja, no se puede salir de la franja propia.",
      "El balon debe progresar de zona en zona con pases.",
      "Trabaja jerarquia posicional y apoyos.",
    ],
  },
  {
    id: "trans-double",
    name: "Transicion doble 4v4",
    category: "transitions",
    objective: "Transiciones rapidas tras recuperacion o perdida.",
    formats: ["football11", "football8", "football7", "futsal"],
    playersMin: 8,
    playersMax: 8,
    durationMin: 15,
    durationMax: 20,
    space: "25 x 20 m con 4 mini-porterias (2 por lado)",
    materials: [
      { name: "Mini-porterias", count: 4 },
      { name: "Petos", count: 8 },
      { name: "Balones", count: 3 },
    ],
    description: [
      "4v4 en el espacio.",
      "Cada vez que se recupera, hay que finalizar en menos de 6 segundos.",
      "Premia las transiciones rapidas y la lectura del momento.",
    ],
  },
  {
    id: "trans-contraataque-3v2",
    name: "Contraataque 3v2 con vuelta 2v1",
    category: "transitions",
    objective: "Eficacia ofensiva en contra + transicion defensiva.",
    formats: ["football11", "football8", "football7"],
    playersMin: 5,
    playersMax: 10,
    durationMin: 12,
    durationMax: 15,
    materials: [
      { name: "Conos", count: 4 },
      { name: "Balones", count: 6 },
      { name: "Porterias", count: 2 },
    ],
    description: [
      "Atacan 3 contra 2 defensores en una porteria.",
      "Tras finalizacion o perdida, los 2 defensores recuperan y atacan 2v1 en la porteria opuesta.",
      "Trabajo de transiciones intercaladas.",
    ],
  },
  {
    id: "press-alta",
    name: "Presion alta a la salida rival",
    category: "pressing",
    objective: "Recuperar la pelota cerca del area rival.",
    formats: ["football11", "football8", "football7", "futsal"],
    playersMin: 8,
    playersMax: 14,
    durationMin: 15,
    durationMax: 20,
    materials: [
      { name: "Conos", count: 6 },
      { name: "Petos", count: 14 },
      { name: "Balones", count: 3 },
      { name: "Porteria", count: 1 },
    ],
    description: [
      "Equipo A (3-4 def + portero) intenta sacar el balon jugado.",
      "Equipo B (3-4 delanteros) presiona alto.",
      "Objetivo de A: superar la linea de medio campo con control.",
      "Objetivo de B: recuperar y finalizar en menos de 6 segundos.",
    ],
  },
  {
    id: "defend-1v1",
    name: "Defensa 1v1 fundamentos",
    category: "defending",
    objective: "Postura, perfil y timing del defensor.",
    formats: ["football11", "football8", "football7", "futsal"],
    playersMin: 8,
    playersMax: 16,
    durationMin: 10,
    durationMax: 12,
    space: "15 x 10 m",
    materials: [
      { name: "Conos", count: 6 },
      { name: "Balones", count: 6 },
    ],
    description: [
      "Atacante con balon conduce hacia el defensor.",
      "Trabajo defensivo: semiflexion, cerrar una salida con el perfil, no lanzarse, usar el cuerpo.",
      "Si el defensor recupera, busca finalizar en porteria pequena (opcional).",
    ],
  },
  {
    id: "set-corner-ofensivo",
    name: "Esquema corner ofensivo",
    category: "setpieces",
    objective: "Llegada coordinada al area en cornes.",
    formats: ["football11", "football8", "football7"],
    playersMin: 6,
    playersMax: 11,
    durationMin: 15,
    durationMax: 20,
    materials: [
      { name: "Balones", count: 10 },
      { name: "Porteria", count: 1 },
      { name: "Petos", count: 6 },
    ],
    description: [
      "Esquema 1: centro al primer palo, remate de cabeza al medio.",
      "Esquema 2: prolongacion al segundo palo.",
      "Esquema 3: balon al punto de penal con bloqueos.",
      "Esquema 4: corto + centro tras superar al rival.",
      "Esquema 5: saque al borde del area para remate de media distancia.",
    ],
  },
  {
    id: "ssg-3v3",
    name: "3v3 en espacio reducido",
    category: "smallsided",
    objective: "Multiplicar duelos, decisiones y finalizaciones.",
    formats: ["football11", "football8", "football7", "futsal"],
    playersMin: 6,
    playersMax: 8,
    durationMin: 20,
    durationMax: 25,
    space: "15 x 20 m",
    materials: [
      { name: "Conos", count: 4 },
      { name: "Mini-porterias", count: 2 },
      { name: "Petos", count: 6 },
      { name: "Balones", count: 3 },
    ],
    description: [
      "4 series de 4 min con 2 min de descanso entre series.",
      "Porterias chicas o porteros.",
      "Reglas opcionales: solo 2 toques, gol vale doble tras 5 pases.",
    ],
  },
  {
    id: "ssg-4-porterias",
    name: "Juego de 4 porterias",
    category: "smallsided",
    objective: "Cambios de orientacion y lectura del juego.",
    formats: ["football11", "football8", "football7", "futsal"],
    playersMin: 6,
    playersMax: 10,
    durationMin: 15,
    durationMax: 20,
    space: "25 x 25 m con 4 mini-porterias (2 por lado)",
    materials: [
      { name: "Mini-porterias", count: 4 },
      { name: "Petos", count: 10 },
      { name: "Balones", count: 2 },
    ],
    description: [
      "Cada equipo defiende 2 porterias y ataca las otras 2.",
      "Premia cambios de orientacion y lectura constante del espacio libre.",
    ],
  },
  {
    id: "gk-circuito",
    name: "Circuito completo de portero",
    category: "goalkeeper",
    objective: "Trabajar las acciones tipicas del portero en serie.",
    formats: ["football11", "football8", "football7", "futsal"],
    playersMin: 1,
    playersMax: 3,
    durationMin: 20,
    durationMax: 25,
    materials: [
      { name: "Conos", count: 6 },
      { name: "Balones", count: 12 },
      { name: "Porteria", count: 1 },
    ],
    description: [
      "1) Desplazamiento + atajada media altura.",
      "2) Estirada al palo derecho.",
      "3) Levantarse + desplazarse + estirada al palo izquierdo.",
      "4) Salida al mano a mano.",
      "5) Recepcion aerea (centro).",
      "6) Saque rapido a banda.",
    ],
    indicators: ["Postura correcta", "Calidad de blocaje", "Comunicacion con la zaga"],
  },
  {
    id: "phys-hiit-balon",
    name: "HIIT con balon",
    category: "physical",
    objective: "Resistencia intermitente especifica.",
    formats: ["football11", "football8", "football7", "futsal"],
    playersMin: 8,
    playersMax: 12,
    durationMin: 20,
    durationMax: 25,
    materials: [
      { name: "Conos", count: 6 },
      { name: "Petos", count: 8 },
      { name: "Balones", count: 2 },
    ],
    description: [
      "Series de 3-4 min al 85-90% del pulso maximo en juego reducido 4v4.",
      "Recuperacion de 1-2 min con pases tranquilos.",
      "4 a 6 series totales.",
    ],
  },
  {
    id: "phys-escalera",
    name: "Coordinacion con escalera",
    category: "physical",
    objective: "Coordinacion, velocidad de pies y agilidad.",
    formats: ["football11", "football8", "football7", "futsal"],
    playersMin: 4,
    playersMax: 16,
    durationMin: 12,
    durationMax: 15,
    materials: [
      { name: "Escalera de coordinacion", count: 2 },
      { name: "Conos", count: 4 },
      { name: "Balones", count: 4 },
    ],
    description: [
      "Patron 1: un pie por cuadro.",
      "Patron 2: dos pies por cuadro.",
      "Patron 3: lateral.",
      "Patron 4: dentro-fuera.",
      "Patron 5: hopscotch (saltos cruzados).",
      "Ultimo tramo: combinar con balon (pase corto al companero).",
    ],
  },
  {
    id: "futsal-bloqueo",
    name: "Bloqueo y continuidad (futsal)",
    category: "futsal-specific",
    objective: "Jugada estandar de futsal con bloqueo y desmarque.",
    formats: ["futsal"],
    playersMin: 4,
    playersMax: 8,
    durationMin: 12,
    durationMax: 15,
    materials: [
      { name: "Conos", count: 4 },
      { name: "Balones", count: 4 },
      { name: "Porteria de futsal", count: 1 },
    ],
    description: [
      "Jugador A conduce, jugador B le hace un bloqueo (cortina).",
      "A queda libre para finalizar o asistir al pivote.",
      "Trabajar timing y posicionamiento del bloqueo.",
    ],
  },
  {
    id: "futsal-3-1",
    name: "Sistema 3-1 de ataque (futsal)",
    category: "futsal-specific",
    objective: "Rotaciones tipicas del sistema 3-1.",
    formats: ["futsal"],
    playersMin: 4,
    playersMax: 8,
    durationMin: 15,
    durationMax: 20,
    materials: [
      { name: "Conos", count: 6 },
      { name: "Petos", count: 4 },
      { name: "Balones", count: 3 },
    ],
    description: [
      "Estructura: cierre + 2 alas + pivote.",
      "Trabajar rotaciones, cambios de posicion, juego con el pivote.",
      "Incluir desmarques al espacio entre lineas.",
    ],
  },
];

export function trainingsByCategory(): { category: TrainingCategory; label: string; items: Training[] }[] {
  const grouped = new Map<TrainingCategory, Training[]>();
  for (const t of trainings) {
    const arr = grouped.get(t.category) ?? [];
    arr.push(t);
    grouped.set(t.category, arr);
  }
  return Array.from(grouped.entries()).map(([category, items]) => ({
    category,
    label: trainingCategoryLabels[category],
    items,
  }));
}

export function findTrainingById(id: string): Training | undefined {
  return trainings.find((t) => t.id === id);
}
